//
//  TaskModel.swift
//  TaskIt
//
//  Created by SANTIPONG TANCHATCHAWAL on 6/24/15.
//  Copyright (c) 2015 SANTIPONG TANCHATCHAWAL. All rights reserved.
//

import Foundation
import CoreData

// This file is automatically generated by selecting TaskItModel.xcdatamodeld and 
// From menu, select Editor and select create NSManagedObject subclass (xcode 6.3.1)

@objc(TaskModel)
class TaskModel: NSManagedObject {

    @NSManaged var completed: NSNumber
    @NSManaged var date: NSDate
    @NSManaged var subtask: String
    @NSManaged var task: String

}
